### ISSUE TITLE
Suggestion: Multi-List Scans

### ISSUE THREAD

**Issue by Volconon** [aheze/OpenFind#8]
I really like that we can out together our own lists, and that the color of the indicator changes depending on the color of the list.
  I think it'd be pretty cool if you could search using two or more lists at the same time, using the color from each list respectively.

  Hope this feedback is helpful.
  Keep up the good work, and have a wonderful day!!!

**Comment by aheze** [comment]
Hey! This is actually already supported — just swipe left on the search bar, and you can add as many search bars as you like! Find will use the list's color as the highlight indicator.

https://user-images.githubusercontent.com/49819455/221392925-8c78eee0-f7c7-4760-8550-82767ae74830.mp4
